// Code generated by mockery v2.53.6. DO NOT EDIT.

package hasensors

import (
	context "context"

	homeassistant "github.com/g-wilson/led/internal/homeassistant"

	mock "github.com/stretchr/testify/mock"
)

// MockStateProvider is an autogenerated mock type for the StateProvider type
type MockStateProvider struct {
	mock.Mock
}

type MockStateProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStateProvider) EXPECT() *MockStateProvider_Expecter {
	return &MockStateProvider_Expecter{mock: &_m.Mock}
}

// GetState provides a mock function with given fields: ctx, entityID
func (_m *MockStateProvider) GetState(ctx context.Context, entityID string) (homeassistant.StateResponse, error) {
	ret := _m.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 homeassistant.StateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (homeassistant.StateResponse, error)); ok {
		return rf(ctx, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) homeassistant.StateResponse); ok {
		r0 = rf(ctx, entityID)
	} else {
		r0 = ret.Get(0).(homeassistant.StateResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStateProvider_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type MockStateProvider_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *MockStateProvider_Expecter) GetState(ctx interface{}, entityID interface{}) *MockStateProvider_GetState_Call {
	return &MockStateProvider_GetState_Call{Call: _e.mock.On("GetState", ctx, entityID)}
}

func (_c *MockStateProvider_GetState_Call) Run(run func(ctx context.Context, entityID string)) *MockStateProvider_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStateProvider_GetState_Call) Return(_a0 homeassistant.StateResponse, _a1 error) *MockStateProvider_GetState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStateProvider_GetState_Call) RunAndReturn(run func(context.Context, string) (homeassistant.StateResponse, error)) *MockStateProvider_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// RunTemplateAreaSensors provides a mock function with given fields: ctx
func (_m *MockStateProvider) RunTemplateAreaSensors(ctx context.Context) ([]homeassistant.AreaSensorsResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunTemplateAreaSensors")
	}

	var r0 []homeassistant.AreaSensorsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]homeassistant.AreaSensorsResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []homeassistant.AreaSensorsResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]homeassistant.AreaSensorsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStateProvider_RunTemplateAreaSensors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunTemplateAreaSensors'
type MockStateProvider_RunTemplateAreaSensors_Call struct {
	*mock.Call
}

// RunTemplateAreaSensors is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStateProvider_Expecter) RunTemplateAreaSensors(ctx interface{}) *MockStateProvider_RunTemplateAreaSensors_Call {
	return &MockStateProvider_RunTemplateAreaSensors_Call{Call: _e.mock.On("RunTemplateAreaSensors", ctx)}
}

func (_c *MockStateProvider_RunTemplateAreaSensors_Call) Run(run func(ctx context.Context)) *MockStateProvider_RunTemplateAreaSensors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStateProvider_RunTemplateAreaSensors_Call) Return(_a0 []homeassistant.AreaSensorsResponse, _a1 error) *MockStateProvider_RunTemplateAreaSensors_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStateProvider_RunTemplateAreaSensors_Call) RunAndReturn(run func(context.Context) ([]homeassistant.AreaSensorsResponse, error)) *MockStateProvider_RunTemplateAreaSensors_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStateProvider creates a new instance of MockStateProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStateProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStateProvider {
	mock := &MockStateProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
