// Code generated by mockery v2.53.6. DO NOT EDIT.

package calendar

import (
	calendar "github.com/g-wilson/led/internal/calendar"
	mock "github.com/stretchr/testify/mock"
)

// MockLoader is an autogenerated mock type for the Loader type
type MockLoader struct {
	mock.Mock
}

type MockLoader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoader) EXPECT() *MockLoader_Expecter {
	return &MockLoader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with no fields
func (_m *MockLoader) Load() ([]calendar.EventSource, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []calendar.EventSource
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]calendar.EventSource, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []calendar.EventSource); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]calendar.EventSource)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockLoader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockLoader_Expecter) Load() *MockLoader_Load_Call {
	return &MockLoader_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockLoader_Load_Call) Run(run func()) *MockLoader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockLoader_Load_Call) Return(_a0 []calendar.EventSource, _a1 error) *MockLoader_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoader_Load_Call) RunAndReturn(run func() ([]calendar.EventSource, error)) *MockLoader_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoader creates a new instance of MockLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoader {
	mock := &MockLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
