// Code generated by mockery v2.53.6. DO NOT EDIT.

package diagnostics

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockPinger is an autogenerated mock type for the Pinger type
type MockPinger struct {
	mock.Mock
}

type MockPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPinger) EXPECT() *MockPinger_Expecter {
	return &MockPinger_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with given fields: ctx, addr
func (_m *MockPinger) Ping(ctx context.Context, addr string) (time.Duration, error) {
	ret := _m.Called(ctx, addr)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 time.Duration
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (time.Duration, error)); ok {
		return rf(ctx, addr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) time.Duration); ok {
		r0 = rf(ctx, addr)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, addr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPinger_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockPinger_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - addr string
func (_e *MockPinger_Expecter) Ping(ctx interface{}, addr interface{}) *MockPinger_Ping_Call {
	return &MockPinger_Ping_Call{Call: _e.mock.On("Ping", ctx, addr)}
}

func (_c *MockPinger_Ping_Call) Run(run func(ctx context.Context, addr string)) *MockPinger_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPinger_Ping_Call) Return(_a0 time.Duration, _a1 error) *MockPinger_Ping_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPinger_Ping_Call) RunAndReturn(run func(context.Context, string) (time.Duration, error)) *MockPinger_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPinger creates a new instance of MockPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPinger {
	mock := &MockPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
