// Code generated by mockery v2.53.6. DO NOT EDIT.

package weather

import (
	context "context"

	weather "github.com/g-wilson/led/internal/weather"
	mock "github.com/stretchr/testify/mock"
)

// MockDayWeatherProvider is an autogenerated mock type for the DayWeatherProvider type
type MockDayWeatherProvider struct {
	mock.Mock
}

type MockDayWeatherProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDayWeatherProvider) EXPECT() *MockDayWeatherProvider_Expecter {
	return &MockDayWeatherProvider_Expecter{mock: &_m.Mock}
}

// GetTwoDayWeatherAtLocation provides a mock function with given fields: ctx, lat, lon
func (_m *MockDayWeatherProvider) GetTwoDayWeatherAtLocation(ctx context.Context, lat string, lon string) (weather.TwoDayWeather, error) {
	ret := _m.Called(ctx, lat, lon)

	if len(ret) == 0 {
		panic("no return value specified for GetTwoDayWeatherAtLocation")
	}

	var r0 weather.TwoDayWeather
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (weather.TwoDayWeather, error)); ok {
		return rf(ctx, lat, lon)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) weather.TwoDayWeather); ok {
		r0 = rf(ctx, lat, lon)
	} else {
		r0 = ret.Get(0).(weather.TwoDayWeather)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, lat, lon)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDayWeatherProvider_GetTwoDayWeatherAtLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTwoDayWeatherAtLocation'
type MockDayWeatherProvider_GetTwoDayWeatherAtLocation_Call struct {
	*mock.Call
}

// GetTwoDayWeatherAtLocation is a helper method to define mock.On call
//   - ctx context.Context
//   - lat string
//   - lon string
func (_e *MockDayWeatherProvider_Expecter) GetTwoDayWeatherAtLocation(ctx interface{}, lat interface{}, lon interface{}) *MockDayWeatherProvider_GetTwoDayWeatherAtLocation_Call {
	return &MockDayWeatherProvider_GetTwoDayWeatherAtLocation_Call{Call: _e.mock.On("GetTwoDayWeatherAtLocation", ctx, lat, lon)}
}

func (_c *MockDayWeatherProvider_GetTwoDayWeatherAtLocation_Call) Run(run func(ctx context.Context, lat string, lon string)) *MockDayWeatherProvider_GetTwoDayWeatherAtLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDayWeatherProvider_GetTwoDayWeatherAtLocation_Call) Return(_a0 weather.TwoDayWeather, _a1 error) *MockDayWeatherProvider_GetTwoDayWeatherAtLocation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDayWeatherProvider_GetTwoDayWeatherAtLocation_Call) RunAndReturn(run func(context.Context, string, string) (weather.TwoDayWeather, error)) *MockDayWeatherProvider_GetTwoDayWeatherAtLocation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDayWeatherProvider creates a new instance of MockDayWeatherProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDayWeatherProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDayWeatherProvider {
	mock := &MockDayWeatherProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
